// Generated by CoffeeScript 1.9.1
(function() {
  module.exports = function(grunt) {
    return grunt.initConfig({
      pkg: grunt.file.readJSON('package.json'),
      meta: {
        banner: '/* <%= pkg.name %> - v<%= pkg.version %> - <%= grunt.template.today("yyyy-mm-dd") %> */'
      },
      connect: {
        server: {
          options: {
            base: './public',
            port: 12345,
            host: '*',
            keepalive: true,
            open: true
          }
        }
      }
    });
  };

}).call(this);
